#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.8

pipelines:
  default:
      - step:
          name: Test
          caches:
            - pip
          script:
            - pip install .
            - pip install responses
            - pip install pytest
            - cd startleft
            - pytest --junitxml=test-reports/report.xml
