trustzones:
  - id:   public-cloud
    name: Public Cloud
    type: public-cloud

# The order of the components is important because parent components must be defined before child components
# TODO: 1- Order shoudn't matter because every object could appear inside other components
components:
  - id:     {$format: "{name}"}
    type:   CD-ACM
    name:   {$path: "_key"}
    $source: {$singleton: {$root: "Resources|squash(@)[?Type=='AWS::CertificateManager::Certificate']"}}
    parent:      public-cloud
    tags:
      - { $path: "Type" }

  - id:     {$format: "{name}"}
    type:   cloudwatch
    name:   {$path: "_key"}
    $source: {$singleton: {$root: "Resources|squash(@)[?Type=='AWS::CloudWatch::Alarm']"}}
    parent:      public-cloud
    tags:
      - { $path: "Type" }

  - id:     {$format: "{name}"}
    type:   {$path: "Type"}
    name:   {$path: "_key"}
    $source: {$root: "Resources|squash(@)[?Type=='AWS::DynamoDB::Table']"}
    parent:      public-cloud
    tags:
      - { $path: "Type" }

  - id:     {$format: "{name}"}
    type:   {$path: "Type"}
    name:   {$path: "_key"}
    $source: {$root: "Resources|squash(@)[?Type=='AWS::EC2::VPC']"}
    parent:      public-cloud
    tags:
      - { $path: "Type" }

  - id:     {$format: "{name}"}
    type:   {$path: "Type"}
    name:   {$path: "_key"}
    $source: {$root: "Resources|squash(@)[?Type=='AWS::EC2::Instance']"}
    parent:      public-cloud
    tags:
      - { $path: "Type" }

  - id:     {$format: "{name}"}
    type:   {$path: "Type"}
    name:   {$path: "_key"}
    $source: {$root: "Resources|squash(@)[?Type=='AWS::EC2::Subnet']"}
    parent:      {$path: "Properties.VpcId.Ref"}
    tags:
      - { $path: "Type" }

  - id:     {$format: "{name}"}
    type:   {$path: "Type"}
    name:   {$path: "_key"}
    $source: {$root: "Resources|squash(@)[?Type=='AWS::EC2::VPCEndpoint']"}
    parent:      {$path: "Properties.VpcId.Ref"}
    tags:
      - { $path: "Type" }

  - id:     {$format: "{name}"}
    type:   {$path: "Type"}
    name:   {$path: "_key"}
    $source: {$root: "Resources|squash(@)[?Type=='AWS::EC2::InternetGateway']"}
    parent:      public-cloud
    tags:
      - { $path: "Type" }

  - id:     {$format: "{name}"}
    type:   {$path: "Type"}
    name:   {$path: "_key"}
    $source: {
      $children: {$path: "Properties.TaskDefinition.Ref"},
      $root: "Resources|squash(@)[?Type=='AWS::ECS::Service']"
    }
    parent:  {$path: "Properties.NetworkConfiguration.AwsvpcConfiguration.Subnets[]|map(&values(@), @)[]"}
    tags:
      - { $path: "Type" }

  - id:     {$format: "{name}"}
    type:   {$path: "Type"}
    name:   {$path: "_key"}
    $source: {$root: "Resources|squash(@)[?Type=='AWS::ECS::TaskDefinition']"}
    parent:  {$parent: {$path: "_key"}}
    tags:
      - { $path: "Type" }

  - id:     {$format: "{name}"}
    type:   {$path: "Type"}
    name:   {$path: "_key"}
    $source: {$root: "Resources|squash(@)[?Type=='AWS::ElasticLoadBalancingV2::LoadBalancer']"}
    parent:  {$path: "Properties.Subnets[]|map(&values(@), @)[]|map(&re_sub('[:]', '-', @), @)"}
    tags:
      - { $path: "Type" }

  - id:     {$format: "{name}"}
    type:   kms
    name:   {$path: "_key"}
    $source: {$singleton: {$root: "Resources|squash(@)[?Type=='AWS::KMS::Key']"}}
    parent:      public-cloud
    tags:
      - { $path: "Type" }

  - id:     {$format: "{name}"}
    type:   {$path: "Type"}
    name:   {$path: "_key"}
    $source: {$root: "Resources|squash(@)[?Type=='AWS::Lambda::Function']"}
    parent:      public-cloud
    tags:
      - { $path: "Type" }

  - id:     {$format: "{name}"}
    type:   cloudwatch
    name:   {$path: "_key"}
    $source: {$singleton: {$root: "Resources|squash(@)[?Type=='AWS::Logs::LogGroup']"}}
    parent:      public-cloud
    tags:
      - { $path: "Type" }


  - id:     {$format: "{name}"}
    type:   {$path: "Type"}
    name:   {$path: "_key"}
    $source: {$root: "Resources|squash(@)[?Type=='AWS::RDS::DBInstance']"}
    parent:      public-cloud
    tags:
      - { $path: "Type" }


  - id:     {$format: "{name}"}
    type:   {$path: "Type"}
    name:   {$path: "_key"}
    $source: {$root: "Resources|squash(@)[?Type=='AWS::Route53::HostedZone']"}
    parent:      public-cloud
    tags:
      - { $path: "Type" }


  - id:     {$format: "{name}"}
    type:   {$path: "Type"}
    name:   {$path: "_key"}
    $source: {$root: "Resources|squash(@)[?Type=='AWS::S3::Bucket']"}
    parent:      public-cloud
    tags:
      - { $path: "Type" }


  - id:     {$format: "{name}"}
    type:   CD-SECRETS-MANAGER
    name:   {$path: "_key"}
    $source: {$singleton: { $root: "Resources|squash(@)[?Type=='AWS::SecretsManager::Secret']"}}
    parent:      public-cloud
    tags:
      - { $path: "Type" }

  - id:     {$format: "{name}"}
    type:   {$path: "Type"}
    name:   {$path: "_key"}
    $source: {$root: "Resources|squash(@)[?Type=='AWS::SQS::Queue']"}
    parent:      public-cloud
    tags:
      - { $path: "Type" }

  - id:     {$format: "{name}"}
    type:   CD-SYSTEMS-MANAGER
    name:   {$path: "_key"}
    $source: {$singleton: {$root: "Resources|squash(@)[?starts_with(Type, 'AWS::SSM')]"}}
    parent:      public-cloud
    tags:
      - { $path: "Type" }

  - id:     {$format: "{name}"}
    type:   {$path: "Type"}
    name:   {$path: "_key"}
    $source: {$root: "Resources|squash(@)[?starts_with(Type, 'AWS::Synthetics')]"}
    parent:  {$path: "Properties.VPCConfig.SubnetIds[]|map(&values(@), @)[]"}
    tags:
      - { $path: "Type" }


  # Default catchall
#  - id:          { $format: "{name}"}
#    $source:
#      $catchall: {$root: "Resources|squash(@)"}
#    type:        {$path: "Type"}
#    name:        {$path: "_key"}
#    parent:      public-cloud
#    tags:
#      - { $path: "Type" }

dataflows: []