trustzones:
  - id:   b61d6911-338d-46a8-9f39-8dcd24abfe91
    name: Public Cloud

 # - id:          {$format: "{type}.{name}.id"}
 #   type:        aws_vpc
 #   $source:     {$root: "resource[].aws_vpc"}
 #   name:        {$path: "keys(@)[0]"}

components:
  - id:          {$format: "{type}.{name}.id"}
    type:        aws_instance
    $source:     {$root: "resource[].aws_instance"}
    name:        {$path: "keys(@)[0]"}
    parent:      {$path: "*.subnet_id[0] | [0] | re_sub('[\\$\\{\\}]', '', @)"}

  - id:          {$format: "{type}.{name}.id"}
    type:        aws_subnet
    $source:     {$root: "resource[].aws_subnet"}
    name:        {$path: "keys(@)[0]"}
    parent:      {$path: "*.vpc_id[0] | [0] | re_sub('[\\$\\{\\}]', '', @)"}

  - id:          {$format: "{type}.{name}.id"}
    type:        aws_route_table
    name:        {$path: "keys(@)[0]"}
    $source:
      $skip:     {$root: "resource[].aws_route_table"}

  - id:          {$format: "{type}.{name}.id"}
    type:        aws_route_table_association
    name:        {$path: "keys(@)[0]"}
    $source:
      $skip:     {$root: "resource[].aws_route_table_association"}

  - id:          {$format: "{type}.{name}.id"}
    type:        aws_security_group
    name:        {$path: "keys(@)[0]"}
    $source:
      $skip:     {$root: "resource[].aws_security_group"}
      
  - id:          {$format: "{type}.{name}.id"}
    type:        aws_security_group_rule
    name:        {$path: "keys(@)[0]"}
    $source:
      $skip:     {$root: "resource[].aws_security_group_rule"}      

  - id:          {$format: "{type}.{name}.id"}
    type:        aws_vpc
    name:        {$path: "keys(@)[0]"}
    $source:
      $skip:     {$root: "resource[].aws_vpc"}
    parent:      b61d6911-338d-46a8-9f39-8dcd24abfe91

  - id:          {$format: "{type}.{name}.id"}
    $source:
      $catchall: {$root: "resource[]"}
    type:        {$path: "keys(@)[0]"}
    name:        {$path: "*|[0]|keys(@)[0]"}
    parent:      b61d6911-338d-46a8-9f39-8dcd24abfe91

dataflows: []