trustzones:
  - type: public
    properties:
      ir.ref: 53c74842-8290-487c-8f7c-ee14ca47dbbd
  - type: private
    properties:
      ir.ref: 359916f7-3501-4f82-85c7-943bebf5f541
  - type: public-cloud
    properties:
      ir.ref: b61d6911-338d-46a8-9f39-8dcd24abfe91

components:

  - type: AWS::WAFRegional::WebACL
    properties:
      ir.componentDefinition.ref: CD-WAF
      style:
        resIcon: mxgraph.aws4.waf

  - type: CD-ACM
    properties:
      ir.componentDefinition.ref: CD-ACM
      style:
        resIcon: mxgraph.aws4.certificate_manager_3

  - type: AWS::Redshift::Cluster
    properties:
      ir.componentDefinition.ref: redshift
      style:
        resIcon: mxgraph.aws4.redshift

  - type: dynamodb
    properties:
      ir.componentDefinition.ref: dynamodb
      style:
        resIcon: mxgraph.aws4.dynamodb

  - type: AWS::KinesisAnalyticsV2::ApplicationCloudWatchLoggingOption
    properties:
      ir.componentDefinition.ref: kinesis-data-analytics
      style:
        resIcon: mxgraph.aws4.kinesis_data_analytics

  - type: AWS::KinesisAnalyticsV2::Application
    properties:
      ir.componentDefinition.ref: kinesis-data-analytics
      style:
        resIcon: mxgraph.aws4.kinesis_data_analytics

  - type: AWS::StepFunctions::Activity
    properties:
      ir.componentDefinition.ref: step-functions
      style:
        resIcon: mxgraph.aws4.step_functions

  - type: AWS::StepFunctions::StateMachine
    properties:
      ir.componentDefinition.ref: step-functions
      style:
        resIcon: mxgraph.aws4.step_functions

  - type: AWS::Cognito::IdentityPool
    properties:
      ir.componentDefinition.ref: cognito
      style:
        resIcon: mxgraph.aws4.cognito

  - type: AWS::Cognito::UserPool
    properties:
      ir.componentDefinition.ref: cognito
      style:
        resIcon: mxgraph.aws4.cognito

  - type: AWS::Cognito::UserPoolClient
    properties:
      ir.componentDefinition.ref: cognito
      style:
        resIcon: mxgraph.aws4.cognito

  - type: AWS::Serverless::Function
    properties:
      ir.componentDefinition.ref: aws-lambda-function
      style:
        resIcon: mxgraph.aws4.lambda

  - type: AWS::KinesisFirehose::DeliveryStream
    properties:
      ir.componentDefinition.ref: kinesis-data-firehose
      style:
        resIcon: mxgraph.aws4.kinesis_data_firehose

  - type: AWS::Kinesis::Stream
    properties:
      ir.componentDefinition.ref: kinesis-data-streams
      style:
        resIcon: mxgraph.aws4.kinesis_data_streams

  - type: AWS::Athena::NamedQuery
    properties:
      ir.componentDefinition.ref: athena
      style:
        resIcon: mxgraph.aws4.athena

  - type: AWS::ApiGateway::RestApi
    properties:
      ir.componentDefinition.ref: api-gateway
      style:
        resIcon: mxgraph.aws4.api_gateway

  - type: AWS::AutoScaling::AutoScalingGroup
    properties:
      ir.componentDefinition.ref: ec2
      style:
        resIcon: mxgraph.aws4.ec2

  - type: AWS::CloudFront::Distribution
    properties:
      ir.componentDefinition.ref: cf-cloudfront
      style:
        resIcon: mxgraph.aws4.cloudfront

  - type: cloudwatch
    properties:
      ir.componentDefinition.ref: cloudwatch
      style:
        resIcon: mxgraph.aws4.cloudwatch

  - type: ec2
    properties:
      ir.componentDefinition.ref: ec2
      style:
        resIcon: mxgraph.aws4.ec2

  - type: vpc
    properties:
      ir.componentDefinition.ref: vpc
      style:
        resIcon: mxgraph.aws4.vpc

  - type: elastic-container-service
    properties:
      ir.componentDefinition.ref: elastic-container-service
      style:
        resIcon: mxgraph.aws4.ecs

  - type: docker-container
    properties:
      ir.componentDefinition.ref: docker-container
      style:
        shape: isoCube

  - type: load-balancer
    properties:
      ir.componentDefinition.ref: load-balancer
      style:
        resIcon: mxgraph.aws4.elastic_load_balancing

  - type: AWS::IAM::ManagedPolicy
    properties:
      ir.componentDefinition.ref: amazon-web-services-environment
      style:
        resIcon: mxgraph.aws4.organizations_account

  - type: kms
    properties:
      ir.componentDefinition.ref: kms
      style:
        resIcon: mxgraph.aws4.key_management_service

  - type: aws-lambda-function
    properties:
      ir.componentDefinition.ref: aws-lambda-function
      style:
        resIcon: mxgraph.aws4.lambda

  - type: rds
    properties:
      ir.componentDefinition.ref: rds
      style:
        resIcon: mxgraph.aws4.rds

  - type: route-53
    properties:
      ir.componentDefinition.ref: route-53
      style:
        resIcon: mxgraph.aws4.route_53

  - type: s3
    properties:
      ir.componentDefinition.ref: s3
      style:
        resIcon: mxgraph.aws4.s3

  - type: sqs-simple-queue-service
    properties:
      ir.componentDefinition.ref: sqs-simple-queue-service
      style:
        resIcon: mxgraph.aws4.sqs

  - type: AWS::SNS::Topic
    properties:
      ir.componentDefinition.ref: sns
      style:
        resIcon: mxgraph.aws4.sns

  - type: CD-SECRETS-MANAGER
    properties:
      ir.componentDefinition.ref: CD-SECRETS-MANAGER
      style:
        resIcon: mxgraph.aws4.secrets_manager

  - type: CD-SYSTEMS-MANAGER
    properties:
      ir.componentDefinition.ref: CD-SYSTEMS-MANAGER
      style:
        resIcon: mxgraph.aws4.systems_manager

  - type: default
    properties:
      ir.componentDefinition.ref: empty-component
      width: 120
      height: 70
      style:
        strokeWidth: 3
        strokeColor: "#B9D0E6"
        fillColor: "#DBEAF7"
        fontColor: "#064C79"
        gradientColor:
        gradientDirection:

dataflows: []
      
