services:
  startleft-docs:
    build:
      context: ..
      dockerfile: deployment/documentation/Dockerfile.documentation
    ports:
      - 8000:8000
    container_name: startleft-docs

  startleft-app:
    build:
      context: ..
      dockerfile: deployment/application/Dockerfile.application
    ports:
      - 5000:5000
    container_name: startleft-app