# This workflow will perform a static code testing with semgrep

name: Static Application Security Testing

on:
  pull_request: {}
  push:
    branches: ["dev", "main"]

jobs:
  semgrep:
    name: Run Semgrep scan with owasp-top-ten & cwe-top-25
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep

    steps:
      - uses: actions/checkout@v3

      - id: semgrep
        run: semgrep ci --config=p/owasp-top-ten --config=p/cwe-top-25 --config=p/gitleaks -q --exclude="tests" --exclude="*/tests" --skip-unknown-extensions --suppress-errors
        continue-on-error: true

      - name: Set failure message vars
        if: steps.semgrep.outcome == 'failure'
        run: echo "icon=fire" >> $GITHUB_ENV

      - name: Set success message vars
        if: steps.semgrep.outcome == 'success'
        run: echo "icon=checkered_flag" >> $GITHUB_ENV

      - name: Semgrep report to Slack
        id: slack-report
        uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 #v1.24.0
        with:
          payload: |
            {
              "text": ":${{ env.icon }}: Semgrep-Startleft-DEV vulnerability test result: ${{ steps.semgrep.outcome }} <https://github.com/${{github.repository}}/commit/${{github.sha}}/checks/${{github.run_id}}|Pipeline logs>"
            }
        env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFICATION_WEBHOOK_URL }}

      - name: Stop if Semgrep finds a vulnerability
        if: steps.semgrep.outcome == 'failure'
        run: exit 1