# This workflow will install Python, StarLeft dependencies and then run StarLeft tests.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Fast Startleft automated testing

on: [workflow_dispatch,push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the project from Git
        uses: actions/checkout@v3

      - name: Get history and tags for SCM versioning to work
        run: |
          git fetch --prune --unshallow
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Update pip version to 23.0.1
        run: python -m pip install --upgrade pip==23.0.1

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Install dependencies
        run: pip install -e ".[setup,test]"

      - name: Test with pytest
        run: |
          python run_tests.py --log-level debug
